name: .NET Core Build & Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - name: Setup .NET Core 3.1.x
      uses: actions/setup-dotnet@v1.8.1
      with:
        dotnet-version: '3.1.x' # SDK Version to use; x will use the latest version of the 3.1 channel
    - name: Setup .NET (global.json)
      uses: actions/setup-dotnet@v1.8.1
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Run UnitTests with dotnet
      run: dotnet test --configuration Release --filter FullyQualifiedName!~Integration